language: php

php:
 - 7.2
 - 7.3
 - 7.4

before_script:
 - composer install

script:
 - vendor/bin/phpunit tests/
 - php tests/Integration/check-samples.php
 - php tests/Integration/check-configurations.php
 - vendor/bin/phpstan analyse src tests
